name: Update Streak Stats

on:
  schedule:
    # Every day at 9:00 AM IST
    - cron: "30 3 * * *"

  workflow_dispatch:

  push:
    paths:
      - ".github/workflows/streak-stats.yml"

concurrency:
  group: profile-stats-update
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Sync with latest main
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Generate Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=tokyonight&hide_border=true&disable_animations=true
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/streak.svg

          git commit -m "Update streak stats" || exit 0

      - name: Push changes
        run: |
          git push origin HEAD:main
